version: '3.8'

services:
  research-code-api:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    container_name: research-code-api-prod
    ports:
      - "80:8000"
    environment:
      - DEBUG=false
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEFAULT_MODEL=gpt-4o-mini
      - MAX_CONCURRENT_REQUESTS=20
      - REQUEST_TIMEOUT=600
    volumes:
      - ../data:/app/data:ro
      - api-logs:/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - research-code-prod
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

  nginx:
    image: nginx:alpine
    container_name: research-code-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - nginx-logs:/var/log/nginx
    depends_on:
      - research-code-api
    restart: always
    networks:
      - research-code-prod

volumes:
  api-logs:
  nginx-logs:

networks:
  research-code-prod:
    driver: bridge
