version: '3.8'

services:
  research-code-api:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    container_name: research-code-api
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    volumes:
      - ../../data:/app/data
      - ../../config:/app/config:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - research-code-network

networks:
  research-code-network:
    driver: bridge
